name: Test Coverage

on: ["push", "pull_request"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.1.0
      
      - name: Use Node 14.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14.x'
      
      - name: Install deps and build
        run: yarn install --frozen-lockfile

      - name: Run test coverage
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
